version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysql_task
    ports:
      - "3306:3306"

  app:
    image: node:latest
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - "db"
    command:
      sh -c 'npm i && node index.js && node /db/create_schema.js'
