version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mysql_task
    ports:
      - "3308:3308"

  api:
    image: node:latest
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

